// <auto-generated />
namespace Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addfieldavatar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfieldavatar));
        
        string IMigrationMetadata.Id
        {
            get { return "202002070502331_add-field-avatar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
